---
- name: install docker
  hosts: docker_host
  become: yes

  tasks:
    - name: Install docker packages
      package:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - docker.io
        - docker-compose

    - name: Ensure docker service is started
      systemd:
        name: docker
        state: stopped